INSERT INTO BOOKS (ID, AUTHORNAME, AUTHORLASTNAME, BOOKNAME, PUBLICATIONDATE) VALUES (1, 'Robert', 'Martin', 'Clean Code', TO_DATE('2008-08-01', 'YYYY-MM-DD'));
INSERT INTO BOOKS (ID, AUTHORNAME, AUTHORLASTNAME, BOOKNAME, PUBLICATIONDATE) VALUES (2, 'David', 'Thomas', 'Pragmatic Programmer', TO_DATE('1999-10-20', 'YYYY-MM-DD'));
INSERT INTO BOOKS (ID, AUTHORNAME, AUTHORLASTNAME, BOOKNAME, PUBLICATIONDATE) VALUES (3, 'Dmitriy', 'Ryaboy', 'The Missing Readme', TO_DATE('2021-08-04', 'YYYY-MM-DD'));
INSERT INTO BOOKS (ID, AUTHORNAME, AUTHORLASTNAME, BOOKNAME, PUBLICATIONDATE) VALUES (4, 'Cay', 'Horstmann', 'Core Java', TO_DATE('2020-07-10', 'YYYY-MM-DD'));
